CC = g++
CFLAGS = -std=c++11 -O2
default: run

run: sum_by_rows sum_by_cols

sum_by_rows: sum_by_rows.cpp
	$(CC) sum_by_rows.cpp -o sum_by_rows $(CFLAGS)
sum_by_cols: sum_by_cols.cpp
	$(CC) sum_by_cols.cpp -o sum_by_cols $(CFLAGS)